server:
  port: 7501

# 配置消费者
spring:
  application:
    name: dm-item-consumer
eureka:
  client:
    service-url:
      defaultZone: http://root:dmw@localhost:7776/eureka/

feign:
  hystrix:
    enabled: true



